---
title: "Attendance list"
author: "Ian May"
date: "August 2, 2018"
output: html_document
---
###{cache = T} only run changed code

```{r setup, include=F}
library(dplyr)
library(ggplot2)
library(scales)
options(stringsAsFactors = F)
```

```{r Dataframe revisions}
attend <- read.csv("attendance_lists - outreach-fy17-18.csv")
attend[attend==""] <- NA
attend$event[attend$event == "Programming Pizza Party (Python/R/Data)"] <- "Programming Pizza Party"
attend$event[attend$event == "Programming Pizza Party (R/Python)"] <- "Programming Pizza Party"
attend$event[attend$event == "LIbrary Carpentry Workshop"] <- "Library Carpentry Workshop"
attend$event[attend$event == "Data VIsual with R"] <- "Data Visual with R"
attend$category[attend$event == "Programming Pizza Party"] <- "programming"
attend$category[attend$event == "Literate Programming"] <- "programming"
attend$category[attend$event == "Data Sharing Bootcamp"] <- "data"
attend$category[attend$event == "Using Data Effectively"] <- "data"
attend$category[attend$event == "Faculty Development: Methods of Empirical Research"] <- "research"
attend$category[attend$event == "Open Refine workshop"] <- "refine"
attend$event[attend$event == "Introducing Los Angeles Region Imagery Acquisition Consortium (LARIAC) Program at UCLA"] <- "Introducing LARIAC Program at UCLA"
attend$event[attend$event == "Faculty Development Workshop: Teaching Transparent Methods of Empirical Research"] <- "Faculty Development: Methods of Empirical Research"
attend$date[attend$event == "Open Refine workshop"] <- "2017-09-22"
attend$status[attend$status == "mlis_student"] <- "grad"
attend$status[attend$status == "mlis student"] <- "grad"
attend$status[attend$status == "mus_student"] <- "grad"
attend$status[attend$status == "curator/staff"] <- "staff"
attend$status[attend$status == "staff; systems specialist"] <- "staff"
attend$status[attend$status == "staff "] <- "staff"
attend$status[attend$status == "visiting scholar"] <- "visiting_scholar"
attend$status[attend$status == "professor"] <- "faculty"
attend$status[attend$status == "visit_scholar"] <- "visiting_scholar"
attend$status[attend$status == "staff/student"] <- "student_staff"
str(attend)

```

```{r Event attendance}
attend %>% 
  group_by(event, category, status) %>% 
  summarize(number_people = n()) %>% 
  ggplot(aes(x=event, y=number_people, fill = status)) + 
    geom_col()+ theme(axis.text.x = element_text(angle = 45, size = 10, hjust = 1)) +labs(title = "Total Attendance Per Event", x= "Event Name", y="Attendance", fill = "Status")

```

```{r Date Attendance}
attend %>% 
  group_by(date, event, category) %>% 
  summarize(number_date = n()) %>% 
   ggplot(aes(x=date, y=number_date, fill= category)) + 
    geom_col()+ theme(axis.text.x = element_text(angle = 45, size = 10, hjust = 1)) + labs(title = "Total Attendance Per Date", x = "Date", y="Attendance")
```

```{r}
attend %>% 
  group_by(status) %>% 
  summarize(number_status = n()) %>% 
   ggplot(aes(x=reorder(status, -number_status), y=number_status)) + 
    geom_col()+ theme(axis.text.x = element_text(angle = 45, size = 10, hjust = 1)) + labs(title = "Total Attendance Per Status", x = "Status", y="Attendance") +geom_text (aes(label=number_status), vjust= -0.5)
```



```{r newchunk}
carpentry <- subset(attend, attend$event == "Library Carpentry Workshop")
carpentry %>% 
  group_by(event, status) %>%
  summarize(number_status = n()) %>% 
  mutate(per = percent(number_status /sum(number_status)))%>% 
  arrange(desc(number_status)) %>% 
  ggplot(aes(x="", y=number_status, fill= status)) +
    geom_bar(width = 1, stat = "identity")+
    coord_polar("y", start = 0)+
    theme_void()+
    geom_text(aes(x=1, y= c(20, 53, 40, 47 , 2.5 , 8 , 59 ), label = per))+ labs(title = "Status of Library Carpentry Workshop Attendees")
  
```  
  


