---
title: "Data Science Center attendance_lists data"
author: 'Ian May UID: 304663145'
date: "December 4, 2018"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}
library(RCurl)
library(dplyr)
library(ggplot2)
library(ggthemes)
attend <- getURL("https://docs.google.com/spreadsheets/d/e/2PACX-1vTxBxubeoxL0jjD0RuPasdhmzhOHXzheJT_U9_UWAQqTdL1fnuaBy1b1J8pPXyCeq-IslHeQepuLyMC/pub?gid=983795958&single=true&output=csv")
attend <- read.csv(textConnection(attend))
```

```{r name changes, warning=FALSE}
attend[attend==""] <- NA
attend$event[attend$event == "Introducing Los Angeles Region Imagery Acquisition Consortium (LARIAC) Program at UCLA"] <- "Introducing LARIAC Program at UCLA"
attend$event[attend$event == "Faculty Development Workshop: Teaching Transparent Methods of Empirical Research"] <- "Faculty Development: Methods of Empirical Research"
attend$role[attend$role == "staff "] <- "staff"
```

```{r event attendance}
attend %>% 
  group_by(event, practice_topic, role) %>% 
  summarize(number_people = n()) %>% 
  ggplot(aes(x=event, y=number_people, fill = role)) + 
    geom_col()+ theme(axis.text.x = element_text(angle = 45, size = 10, hjust = 1)) +labs(title = "Total Attendance Per Event", x= "Event Name", y="Attendance", fill = "Role")
```


```{r Attendance per date}
attend %>% 
  group_by(date, event, practice_topic) %>% 
  summarize(number_date = n()) %>% 
   ggplot(aes(x=date, y=number_date, fill= practice_topic)) + 
    geom_col()+ theme(axis.text.x = element_text(angle = 45, size = 8, hjust = 1)) + labs(title = "Total Attendance Per Date", x = "Date", y="Attendance")
```


```{r Attendance per Role}
attend %>% 
  group_by(role) %>% 
  summarize(number_role = n()) %>% 
   ggplot(aes(x=reorder(role, -number_role), y=number_role)) + 
    geom_col()+ theme(axis.text.x = element_text(angle = 45, size = 10, hjust = 1)) + labs(title = "Total Attendance Per Role", x = "Role", y="Attendance") +geom_text (aes(label=number_role), vjust= -0.5)
```

```{r ucla department attendance}
ucla <- subset(attend, attend$institution =="ucla")
ucla %>% 
  group_by(dept) %>% 
  summarize(number_dept = n()) %>%
   ggplot(aes(x=reorder(dept, number_dept), y=number_dept)) + 
    geom_bar(stat = "identity")+ 
    theme(axis.text.x = element_text(size = 10, hjust = 1)) +
    labs(title = "UCLA Department Attendance", x = "Dept", y="Attendance")+
    geom_text (aes(label=number_dept), vjust= -0.5)+
    coord_flip()
```


```{r}
no_ucla <- subset(attend, attend$institution != "ucla" )
g <- ggplot(no_ucla, aes(institution))
g + geom_bar(aes(fill=role), width = 0.5) + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) +
  labs(title="Attendance by Institution", 
       subtitle="Including role")
n <- as.data.frame(table(no_ucla$institution))
n <- n[order(-n$Freq),]
n[1:10,]
n$Var1[n$Freq==1]

```

